# Any sensitive information can be placed in this file
# 1. Database information referenced by database.yml MUST be here
#     NO DATABASE INFORMATION SHOULD BE PLACED IN database.yml
# 2. Other information can also be placed in this folder
#     I.e., Secret Tokens to prevent attacks on the application

secretname: "This is a secret in all environments"

development:
  adapter: "sqlite3"
  database: "db/development.sqlite3"
  pool: "5"
  timeout: "5000"

test:
  adapter: "sqlite3"
  database: "db/test.sqlite3"
  pool: "5"
  timeout: "5000"

production:
  adapter: "sqlite3"
  database: "db/development.sqlite3"
  pool: "5"
  timeout: "5000"